version: "3"
services:
    lumba-fe:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        container_name: lumba-fe
        env_file: ".env"
        ports:
            - "3000:3000"
